FROM python:3.12-slim

WORKDIR /var/task

COPY requirements.txt .

RUN pip install \
    --no-cache-dir \
    -r requirements.txt

COPY app ./app
COPY api_handler.py .

ENTRYPOINT ["python", "-m", "awslambdaric"]
CMD ["api_handler.handler"]