FROM python:3.12-slim

# Install Tesseract and required system libraries
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        tesseract-ocr \
        tesseract-ocr-eng \
        libgl1 \
        libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/task

COPY requirements.txt .

RUN pip install \
    --no-cache-dir \
    -r requirements.txt

COPY app ./app
COPY lambda_handler.py .

ENTRYPOINT ["python", "-m", "awslambdaric"]
CMD ["lambda_handler.handler"]